### ISSUE TITLE
Why is resource usage very low, Does it use gpu or cpu?

### ISSUE THREAD

**Issue by monitor22** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#13]
Can I let it use more GPU?
![2024-27 23_52_40](https://github.com/user-attachments/assets/9a47c419-85c9-4a67-b21f-fd475f468aff)

**Comment by TugdualKerjan** [comment]
Increase your batch size and watch the magic happen ! It's an empiracal process but quite effiicent ;)

**Comment by nguyenhoanganh2002** [comment]
> Can I let it use more GPU? ![2024-27 23_52_40](https://private-user-images.githubusercontent.com/112599327/371639961-9a47c419-85c9-4a67-b21f-fd475f468aff.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjc1MTU1NDIsIm5iZiI6MTcyNzUxNTI0MiwicGF0aCI6Ii8xMTI1OTkzMjcvMzcxNjM5OTYxLTlhNDdjNDE5LTg1YzktNGE2Ny1iMjFmLWZkNDc1ZjQ2OGFmZi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTI4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkyOFQwOTIwNDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03NmVjYjk5NTU4NDc2NjUxYTgxMjg4NmFmNDllOGQ0MTg2NGE2NzU2NmQ4MzZjZDc1MWEyYmY4NWU3MzcyZjlmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.4dtpXpXJS3cLKvmdXzDkTajGAEujFbfD4OUVY_YqJCc)

@TugdualKerjan has answered your question :))

**Comment by monitor22** [comment]
I have increased the batch size to 128 and its been like this for ~12 hours.

![image](https://github.com/user-attachments/assets/64820359-8448-4ed0-82e9-828eca3ba6bc)

**Comment by nguyenhoanganh2002** [comment]
It appears that the training process may not be utilizing the GPU as expected. Here are some steps to diagnose and potentially resolve the problem:

1. Check GPU availability:
   Run `torch.cuda.is_available()` to verify if PyTorch can detect an available GPU.

2. Verify CUDA installation:
   Ensure that CUDA is properly installed on your system and that your PyTorch version is built with CUDA support. You can check this by running:
   ```python
   import torch
   print(torch.__version__)
   print(torch.version.cuda)
   ```
