### ISSUE TITLE
xử lý file âm thanh khi training

### ISSUE THREAD

**Issue by vcstack** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#14]
Xin chào bạn, 
Bạn có thể chỉ giúp mình các bước mà bạn sẽ xử lý các file âm thanh trước khi thực hiện training như thế nào được không?
Thank you

**Comment by nguyenhoanganh2002** [comment]
> Xin chào bạn, Bạn có thể chỉ giúp mình các bước mà bạn sẽ xử lý các file âm thanh trước khi thực hiện training như thế nào được không? Thank you

Mình chỉ loại bỏ âm thanh background bằng https://github.com/nomadkaraoke/python-audio-separator thôi bạn

**Comment by vcstack** [comment]
@nguyenhoanganh2002 Hi Bạn
Mình muốn hỏi thêm là về các file âm thanh thì sẽ split nó ra thành các file 10s, hay là sẽ split nó theo từng câu vậy?
