### ISSUE TITLE
RuntimeError: Error(s) in loading state_dict for Xtts

### ISSUE THREAD

**Issue by saan04** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#15]
Getting missing and unexpected keys on loading from the fine tuned model config and checkpoint

**Comment by nguyenhoanganh2002** [comment]
> Getting missing and unexpected keys on loading from the fine tuned model config and checkpoint

Could you provide more details about the error traceback?

**Comment by saan04** [comment]
I tried to use the coqui-tts folder api for XTTS itself which gave this error but on cloning your repository and running the code have listed it worked fine. 
Sorry for the trouble.
