### ISSUE TITLE
Training new language sk=slovak language 

### ISSUE THREAD

**Issue by JohnF51** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#17]
Hi Nguyễn Hoàng Anh
I would like to ask you if you could help me and create a detailed tutorial for training a new language that is not yet supported by XTTSv2. The Slovak language is very similar to the Czech language which is already supported can this be used somehow? What would you recommend? I have Slovak voice wav data. How to modify your script so that I can use the Czech pre-trained model and modify it to the new "Slovak" language, Is it possible? Thank you for your great work.

**Comment by nguyenhoanganh2002** [comment]
> Hi Nguyễn Hoàng Anh I would like to ask you if you could help me and create a detailed tutorial for training a new language that is not yet supported by XTTSv2. The Slovak language is very similar to the Czech language which is already supported can this be used somehow? What would you recommend? I have Slovak voice wav data. How to modify your script so that I can use the Czech pre-trained model and modify it to the new "Slovak" language, Is it possible? Thank you for your great work.

I think in your case there is no need to extend the tokenizer vocabulary. Just set the language to Czech by using `--language="cs"`
