### ISSUE TITLE
Dataset size

### ISSUE THREAD

**Issue by lukaszliniewicz** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#18]
How much audio have you used to obtain decent results?

**Comment by nguyenhoanganh2002** [comment]
> How much audio have you used to obtain decent results?

I've found that approximately 100 hours of audio data are necessary to achieve satisfactory results.

**Comment by desis123** [comment]
> I've found that approximately 100 hours of audio data are necessary to achieve satisfactory results.

That 100 hours need to be one person's voice ? Or I can use multiple person voices to make that 100 hours ?
