### ISSUE TITLE
Text preprocessing

### ISSUE THREAD

**Issue by ScottishFold007** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#3]
Text preprocessing. If the data is not in English, does the text need some processing? For example, should Chinese text be converted to Pinyin?

**Comment by nguyenhoanganh2002** [comment]
> Text preprocessing. If the data is not in English, does the text need some processing? For example, should Chinese text be converted to Pinyin?

You don't need to convert Chinese text to Pinyin. But its high recommendly to normalize text such as number, special characters to word. Fortunately, coqui supported it for Chinese [https://github.com/nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages/blob/95866555d61dba2ddb014af4af51e58ba6aade78/TTS/tts/layers/xtts/zh_num2words.py](url)
