### ISSUE TITLE
Incorrect naming for DVAE training 

### ISSUE THREAD

**Issue by C00reNUT** [nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages#6]
In dvae training and dvae.sh script is selected incorrect .py file

It shall be `train_dvae_xtts.py` instead of `train_gpt_xtts.py`...

I am away from my computer so I cannot make pull request, so just an issue...

**Comment by nguyenhoanganh2002** [comment]
> In dvae training and dvae.sh script is selected incorrect .py file
> 
> It shall be `train_dvae_xtts.py` instead of `train_gpt_xtts.py`...
> 
> I am away from my computer so I cannot make pull request, so just an issue...

Thanks for notifying me. I fixed it.
https://github.com/nguyenhoanganh2002/XTTSv2-Finetuning-for-New-Languages/commit/861be1f2e8c7102d6558eba2d7287b15346608b3
